Join card component
acm-ucr/hiss-website pull request #18
Opened 2023-10-21 04:45 UTC by achen409

![image](https://github.com/acm-ucr/hiss-website/assets/85457506/fb5fc458-868b-45c0-917c-e7c9f5826e67)

2023-10-21 20:10 UTC, SafeDuck commented
https://tailwindcss.com/docs/box-shadow

Add a box shadow like how it is in the figma

2023-10-21 22:02 UTC, achen409 commented
![image](https://github.com/acm-ucr/hiss-website/assets/85457506/93dcf42f-97b0-44d7-9ac0-adfbebf22ba8)

2023-10-22 01:44 UTC, SafeDuck commented on src/components/about/Card.jsx
> +        <FaDiscord className="text-7xl" />
make it hiss-purple

2023-10-22 02:26 UTC, achen409 commented
![image](https://github.com/acm-ucr/hiss-website/assets/85457506/4f029583-568b-4707-ac06-5f4000ce0e34)

2023-10-22 18:26 UTC, SafeDuck commented on src/components/about/Card.jsx
>  const Card = () => {
CSS is good. Now add props: {text, icon, link} 

example of how to use these props: https://github.com/acm-ucr/asme-website/blob/dev/src/components/home/JoinCard.jsx

2023-10-24 22:34 UTC, SafeDuck requested changes

2023-10-24 22:34 UTC, SafeDuck commented on src/components/about/Card.jsx
> +    <div className="bg-white flex flex-col items-center justify-top pt-4 pb-12 w-48 h-1/4 rounded-lg border-1 shadow-lg">
remove justify-top, and h-1/4

2023-10-25 20:30 UTC, achen409 commented
![image](https://github.com/acm-ucr/hiss-website/assets/85457506/b94ea1af-8c8b-457b-b756-23188dc520e5)

2023-10-26 08:12 UTC, SafeDuck approved these changes

2023-10-26 08:12 UTC, merged