Completed Title component
acm-ucr/hiss-website pull request #19
Opened 2023-10-22 02:09 UTC by kavinphab

2023-10-22 20:15 UTC, kavinphab commented
![image](https://github.com/acm-ucr/hiss-website/assets/29679531/998f3e88-a9cd-499f-9b77-2a166f7f8379)

2023-10-22 20:33 UTC, SafeDuck requested changes

2023-10-22 20:33 UTC, SafeDuck commented on src/components/Title.jsx
> +    <div className="">
what's this empty div for?

2023-10-22 20:33 UTC, SafeDuck commented on src/app/page.js
> +  return <Title title="Meet the Team" />;
make sure you remove this before we merge

2023-10-22 21:02 UTC, SafeDuck requested changes

2023-10-22 21:02 UTC, SafeDuck commented on src/components/Title.jsx
> +      <div className="text-white text-right pr-7 pt-3 font-poppins font-bold text-2xl h-16 w-2/5 bg-gradient-to-r from-hiss-blue to-hiss-purple rounded-r-full">
change the font to text-3xl

2023-10-24 23:20 UTC, SafeDuck approved these changes

2023-10-24 23:20 UTC, merged