formating
acm-ucr/hiss-website pull request #29
Opened 2023-11-02 01:41 UTC by kavinphab

2023-11-02 08:09 UTC, SafeDuck commented
bruh put a screenshot

2023-11-02 22:11 UTC, kavinphab commented
![image](https://github.com/acm-ucr/hiss-website/assets/29679531/3de867b4-8b4e-474c-8f32-8515721b6143)

2023-11-02 23:13 UTC, SafeDuck requested changes

2023-11-02 23:13 UTC, SafeDuck commented on src/components/Footer.jsx
> +          {<FaInstagram className="text-2xl" />}{" "}
things to add:
1. when hovered, make cursor pointer
2. when clicked, takes you to dummy links for now

2023-11-04 04:45 UTC, SafeDuck approved these changes

2023-11-04 04:46 UTC, merged